server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ps1437/microservice-design-pattern.git
          search-paths: ms-gateway-external-config/config-repo
