server:
  port : 8888

spring:
  application:
    name: configserver

config:
  server:
    type: FILESYSTEM
    path: "C:\\praveeen\\preperation\\ms-design\\ms-custom-cloud-config\\ms-custom-cloud-config\\src\\main\\resources\\config-repo"
    default-label: main
    refresh-enabled: true
