server:
  port : 8761

spring:
  application:
    name : Eureka-INDA

eureka:
  instance:
    hostname: eureka-india
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
  server:
    evictionIntervalTimerInMs: 50000
  datacenter: DS-INDIA
  availabilityZones:
    DS-INDIA: india
