server:
  port : 8888

spring:
  application:
    name: configserver

file-loader:
  type: FILESYSTEM
  path: "C:\\praveeen\\preperation\\ms-custom-cloud-config\\ms-custom-cloud-config\\src\\main\\resources\\config-repo"
