server:
  port: 8085

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      httpclient:
        connect-timeout: 5000  # 5 seconds
        response-timeout: 10s   # 10 seconds
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: account-service
          uri: lb://ACCOUNT-SERVICE  # Load balancing via Eureka
          predicates:
            - Path=/accounts/**
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/customers/**
#            - Method=GET,POST
#            - Header=X-Request-Id, \d+
#            - Query=param, value
#            - RemoteAddr=192.168.1.1/24
#            - After=2024-01-01T00:00:00+00:00[UTC]
#            - Before=2024-12-31T23:59:59+00:00[UTC]
#          filters:
#            - AddRequestHeader=X-Custom-Header, CustomValue
#            - AddResponseHeader=X-Response-Header, ResponseValue
#            - RewritePath=/old/(.*), /new/$1
#            - RequestRateLimiter=3, 10
#            - Retry=3,500ms,502,503  # 3 retries, 500ms interval, for HTTP 502 and 503 errors

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone:
        - http://localhost:8761/eureka/
        - http://localhost:8762/eureka/

    # Enable retry mechanism for failover
    eurekaServerConnectTimeoutSeconds: 5  # Connection timeout
    eurekaServerReadTimeoutSeconds: 5     # Read timeout
    eurekaServerTotalConnections: 5
    eurekaServerTotalConnectionsPerHost: 5
    registryFetchIntervalSeconds: 10  # Refresh registry every 10 seconds

  instance:
    preferIpAddress: true  # Ensures better discovery
    leaseRenewalIntervalInSeconds: 10  # Heartbeat interval
    leaseExpirationDurationInSeconds: 30  # Timeout before removal
    metadataMap:
      zone: zone1  # Zone-awareness

springdoc:
  swagger-ui:
    urls:
      - name: Account Service
        url: /account/v3/api-docs
      - name: Customer Service
        url: /customer/v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true