server:
  port: 8085

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: lb://ACCOUNT-SERVICE  # Load balancing via Eureka
          predicates:
            - Path=/accounts/**
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE # Load balancing via Eureka
          predicates:
            - Path=/customers/**


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone:
        - http://localhost:8761/eureka/
        - http://localhost:8762/eureka/

    # Enable retry mechanism for failover
    eurekaServerConnectTimeoutSeconds: 5  # Connection timeout
    eurekaServerReadTimeoutSeconds: 5     # Read timeout
    eurekaServerTotalConnections: 5
    eurekaServerTotalConnectionsPerHost: 5
    registryFetchIntervalSeconds: 10  # Refresh registry every 10 seconds

  instance:
    preferIpAddress: true  # Ensures better discovery
    leaseRenewalIntervalInSeconds: 10  # Heartbeat interval
    leaseExpirationDurationInSeconds: 30  # Timeout before removal
    metadataMap:
      zone: zone1  # Zone-awareness

springdoc:
  swagger-ui:
    urls:
      - name: Account Service
        url: /account/v3/api-docs
      - name: Customer Service
        url: /customer/v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: "*"